// <auto-generated />
using System;
using DLPR.LicensePlateData.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DLPR.LicensePlateData.DbMigrations.Migrations
{
    [DbContext(typeof(DLPRLicensePlateDbContext))]
    partial class DLPRLicensePlateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DLPR.LicensePlateData.Domain.Entities.LicensePlate", b =>
                {
                    b.Property<string>("Kenteken")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("API_Gekentekende_voertuigen_assen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("API_Gekentekende_voertuigen_brandstof")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("API_Gekentekende_voertuigen_carrosserie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("API_Gekentekende_voertuigen_carrosserie_specifiek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("API_Gekentekende_voertuigen_voertuigklasse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Aanhangwagen_autonoom_geremd")
                        .HasColumnType("int");

                    b.Property<int?>("Aanhangwagen_middenas_geremd")
                        .HasColumnType("int");

                    b.Property<int?>("Aantal_cilinders")
                        .HasColumnType("int");

                    b.Property<int?>("Aantal_deuren")
                        .HasColumnType("int");

                    b.Property<int?>("Aantal_rolstoelplaatsen")
                        .HasColumnType("int");

                    b.Property<int?>("Aantal_staanplaatsen")
                        .HasColumnType("int");

                    b.Property<int?>("Aantal_wielen")
                        .HasColumnType("int");

                    b.Property<int?>("Aantal_zitplaatsen")
                        .HasColumnType("int");

                    b.Property<int?>("Afstand_hart_koppeling_tot_achterzijde_voertuig")
                        .HasColumnType("int");

                    b.Property<int?>("Afstand_voorzijde_voertuig_tot_hart_koppeling")
                        .HasColumnType("int");

                    b.Property<int?>("Afwijkende_maximum_snelheid")
                        .HasColumnType("int");

                    b.Property<int?>("Breedte")
                        .HasColumnType("int");

                    b.Property<string>("Breedte_voertuig_maximum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Breedte_voertuig_minimum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Bruto_BPM")
                        .HasColumnType("int");

                    b.Property<int?>("Catalogusprijs")
                        .HasColumnType("int");

                    b.Property<int?>("Cilinderinhoud")
                        .HasColumnType("int");

                    b.Property<string>("Code_toelichting_tellerstandoordeel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Datum_eerste_tenaamstelling_in_Nederland")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Datum_eerste_tenaamstelling_in_Nederland_DT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Datum_eerste_toelating")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Datum_eerste_toelating_DT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Datum_tenaamstelling")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Datum_tenaamstelling_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("Eerste_kleur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Europese_uitvoeringcategorie_toevoeging")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Europese_voertuigcategorie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Europese_voertuigcategorie_toevoeging")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Export_indicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Handelsbenaming")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Hoogte_voertuig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hoogte_voertuig_maximum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hoogte_voertuig_minimum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inrichting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jaar_laatste_registratie_tellerstand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Laadvermogen")
                        .HasColumnType("int");

                    b.Property<int?>("Lengte")
                        .HasColumnType("int");

                    b.Property<string>("Lengte_voertuig_maximum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lengte_voertuig_minimum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Massa_bedrijfsklaar_maximaal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Massa_bedrijfsklaar_minimaal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Massa_ledig_voertuig")
                        .HasColumnType("int");

                    b.Property<int?>("Massa_rijklaar")
                        .HasColumnType("int");

                    b.Property<int?>("Maximale_constructiesnelheid")
                        .HasColumnType("int");

                    b.Property<string>("Maximum_last_onder_de_voorassen_tezamenkoppeling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Maximum_massa_samenstelling")
                        .HasColumnType("int");

                    b.Property<string>("Maximum_massa_technisch_maximaal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maximum_massa_technisch_minimaal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Maximum_massa_trekken_ongeremd")
                        .HasColumnType("int");

                    b.Property<decimal?>("Maximum_ondersteunende_snelheid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Maximum_trekken_massa_geremd")
                        .HasColumnType("int");

                    b.Property<string>("Merk")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Openstaande_terugroepactie_indicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Oplegger_geremd")
                        .HasColumnType("int");

                    b.Property<string>("Plaats_chassisnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Registratie_datum_goedkeuring_afschrijvingsmoment_BPM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Registratie_datum_goedkeuring_afschrijvingsmoment_BPM_DT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rupsonderstelconfiguratiecode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subcategorie_Nederland")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Taxi_indicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Technisch_toelaatbaar_massa_koppelpunt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Technische_max_massa_voertuig")
                        .HasColumnType("int");

                    b.Property<string>("Tellerstandoordeel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenaamstellen_mogelijk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Toegestane_maximum_massa_voertuig")
                        .HasColumnType("int");

                    b.Property<string>("Tweede_kleur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type_gasinstallatie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type_remsysteem_voertuig_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typegoedkeuringsnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uitvoering")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Variant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Vermogen_massarijklaar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Verticale_belasting_koppelpunt_getrokken_voertuig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vervaldatum_APK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Vervaldatum_APK_DT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Vervaldatum_tachograaf")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Vervaldatum_tachograaf_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("Voertuigsoort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volgnummer_wijziging_EU_typegoedkeuring")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WAM_verzekerd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wacht_op_keuren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Wielbasis")
                        .HasColumnType("int");

                    b.Property<string>("Wielbasis_voertuig_maximum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wielbasis_voertuig_minimum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zuinigheidsclassificatie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Kenteken");

                    b.HasIndex("Handelsbenaming");

                    b.HasIndex("Merk");

                    b.ToTable("LicensePlates");
                });
#pragma warning restore 612, 618
        }
    }
}
